### ISSUE TITLE
批量下载的文件名会乱码

### ISSUE THREAD

**Issue by garyvalue** [LennoC/N_m3u8DL-RE_SimpleBatGUI#1]
input.txt格式为
蜘蛛侠1,https://xxx.com/c5b55edc1acd183113e55ba37fc75b3a/4998973zZY8hj2q_ia57089e87ab96cfcbae2e1bed2cdf0db.m3u8
蜘蛛侠2,https://xxx.com/c5b55edc1acd183113e55ba37fc75b3a/4998973zZY8hj2q_ia57089e87ab96cfcbae2e1bed2cdf0db.m3u8

output.bat为
TITLE "1/2 - 铚樿洓渚?" 
N_m3u8DL-RE "https://xxx.com/c5b55edc1acd183113e55ba37fc75b3a/4998973zZY8hj2q_ia57089e87ab96cfcbae2e1bed2cdf0db.m3u8" --save-name "铚樿洓渚?" --tmp-dir "D:\Downloads\New\N_m3u8DL_Temp" --save-dir "D:\Downloads\New" --ffmpeg-binary-path "ffmpeg.exe" --download-retry-count:9 --auto-select:true --check-segments-count:false --no-log:true --append-url-params:true -mt:true --mp4-real-time-decryption:true --ui-language:zh-CN 
TITLE "2/2 - 铚樿洓渚?" 
N_m3u8DL-RE "https://xxx.com/c5b55edc1acd183113e55ba37fc75b3a/4998973zZY8hj2q_ia57089e87ab96cfcbae2e1bed2cdf0db.m3u8" --save-name "铚樿洓渚?" --tmp-dir "D:\Downloads\New\N_m3u8DL_Temp" --save-dir "D:\Downloads\New" --ffmpeg-binary-path "ffmpeg.exe" --download-retry-count:9 --auto-select:true --check-segments-count:false --no-log:true --append-url-params:true -mt:true --mp4-real-time-decryption:true --ui-language:zh-CN

**Comment by LennoC** [comment]
是否保存为ANSI编码？
保存为ANSI编码后再试试。
