### ISSUE TITLE
与64位版本的windows不兼容

### ISSUE THREAD

**Issue by garyvalue** [LennoC/N_m3u8DL-RE_SimpleBatGUI#3]
![QQ图片20240627150359](https://github.com/LennoC/N_m3u8DL-RE_SimpleBatGUI/assets/38098459/3dc5ae31-d6ed-4609-b7a4-191167371858)

**Comment by garyvalue** [comment]
Windows 11 专业版
版本号23H2
操作系统版本22631.3737

**Comment by LennoC** [comment]
换release版或者最新的action版试试吧，我这边没问题。
最新的action地址： https://github.com/nilaoda/N_m3u8DL-RE/actions/runs/9626651566/artifacts/1627746703

**Comment by garyvalue** [comment]
>  最新的action地址： https://github.com/nilaoda/N_m3u8DL-RE/actions/runs/9626651566/artifacts/1627746703
这个没问题
