### ISSUE TITLE
大佬，我使用批量下载报错了，麻烦您空了看一下呀

### ISSUE THREAD

**Issue by 1229984599** [LennoC/N_m3u8DL-RE_SimpleBatGUI#4]
### 这是我的intput.txt
```bash
国民音乐教育的目标与路径-周海宏,https://tianyicache.gensee.com/gsgetrecord/record68.gensee.net/gsrecord/183681/upload/2024_07_09/67538201_1720518541/hls/record1.m3u8
识谱与乐理教学建议-周海宏,https://tianyicache.gensee.com/gsgetrecord/record68.gensee.net/gsrecord/183681/upload/2024_07_09/67538201_1720542623/hls/record1.m3u8
音乐欣赏课教学建议-周海宏,https://tianyicache.gensee.com/gsgetrecord/record68.gensee.net/gsrecord/183681/upload/2024_07_09/67538201_1720533649/hls/record1.m3u8
do re mi之歌-施程程,https://tianyicache.gensee.com/gsgetrecord/record68.gensee.net/gsrecord/183681/upload/2024_08_19/67538201_1724034253/hls/record1.m3u8
小九的旋律密码-杨扬 杨文立,https://tianyicache.gensee.com/gsgetrecord/record68.gensee.net/gsrecord/183681/upload/2024_07_09/67538201_1720548760/hls/record1.m3u8
低年级节奏教学的探索与实验-郑杨 果艳丽,https://tianyicache.gensee.com/gsgetrecord/record68.gensee.net/gsrecord/183681/upload/2024_07_09/67538201_1720555922/hls/record1.m3u8
```
### 错误截图
![image](https://github.com/user-attachments/assets/ab4d8ac1-6561-4103-91ce-c24056ab74a1)

**Comment by LennoC** [comment]
input文件编码问题，转为ANSI后可正常识别。
因为bat基本只认ANSI编码，而Win10后新建文本默认utf8，所以需要转一下编码。
文本编辑器打开input另存的时候右下角的编码处选择改为ANSI后保存。
再运行一次应该就正常了。

晚些时候我看下怎么处理这个问题。

**Comment by LennoC** [comment]
Windows和批处理的本身限制，专门去处理输入文件的编码识别转换过于麻烦，做了个小更新，在批量下载的过程中加入了一些提示。

**Comment by LennoC** [comment]
@1229984599 
已尝试将编码环境改为UTF8，现在应该都正常了，不再需要特意去将TXT修改编码为ANSI。
请下载这个版本的文件。 [N_m3u8DL-RE_SimpleBatGUI-UTF8.bat](https://raw.githubusercontent.com/LennoC/N_m3u8DL-RE_SimpleBatGUI/main/N_m3u8DL-RE_SimpleBatGUI-UTF8.bat)

**Comment by 1229984599** [comment]
> @1229984599 已尝试将编码环境改为UTF8，现在应该都正常了，不再需要特意去将TXT修改编码为ANSI。 请下载这个版本的文件。 [N_m3u8DL-RE_SimpleBatGUI-UTF8.bat](https://raw.githubusercontent.com/LennoC/N_m3u8DL-RE_SimpleBatGUI/main/N_m3u8DL-RE_SimpleBatGUI-UTF8.bat)

收到，大佬辛苦啦😄
